default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 12345678
  host: localhost

development:
  <<: *default
  database: rails_avancado_development


test:
  <<: *default
  database: rails_avancado_teste

production:
  <<: *default
  database: rails_avancado_production
